// Date: 10.06.2013 20:51:49
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package aroma1997.compactwindmills.rotors;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRotor extends ModelBase
{
  //fields
    ModelRenderer axis;
    ModelRenderer arm1;
    ModelRenderer arm2;
    ModelRenderer arm3;
    ModelRenderer arm4;
  
  public ModelRotor()
  {
    textureWidth = 32;
    textureHeight = 64;
    
      axis = new ModelRenderer(this, 0, 0);
      axis.addBox(-1F, 0F, -1F, 2, 7, 2);
      axis.setRotationPoint(0F, 0F, 0F);
      axis.setTextureSize(32, 64);
      axis.mirror = true;
      setRotation(axis, 0F, 0F, 1.570796F);
      arm1 = new ModelRenderer(this, 0, 0);
      arm1.addBox(0F, 0F, -4F, 1, 32, 8);
      arm1.setRotationPoint(-8F, 0F, 0F);
      arm1.setTextureSize(32, 64);
      arm1.mirror = true;
      setRotation(arm1, 0F, -0.3926991F, 0F);
      arm2 = new ModelRenderer(this, 0, 0);
      arm2.addBox(0F, 0F, -4F, 1, 32, 8);
      arm2.setRotationPoint(-8F, 0F, 0F);
      arm2.setTextureSize(32, 64);
      arm2.mirror = true;
      setRotation(arm2, 1.570796F, 0F, -0.3926991F);
      arm3 = new ModelRenderer(this, 0, 0);
      arm3.addBox(0F, 0F, -4F, 1, 32, 8);
      arm3.setRotationPoint(-8F, 0F, 0F);
      arm3.setTextureSize(32, 64);
      arm3.mirror = true;
      setRotation(arm3, -1.570796F, 0F, 0.3926991F);
      arm4 = new ModelRenderer(this, 0, 0);
      arm4.addBox(0F, 0F, -4F, 1, 32, 8);
      arm4.setRotationPoint(-8F, 0F, 0F);
      arm4.setTextureSize(32, 64);
      arm4.mirror = true;
      setRotation(arm4, 3.141593F, 0.3926991F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    axis.render(f5);
    arm1.render(f5);
    arm2.render(f5);
    arm3.render(f5);
    arm4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
